plugins {
    id 'java'
    id 'application'
}

group = 'com.ebac'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'com.ebac.modulo55.Main'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
